version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  search-service:
    image: ${REGISTRY:-flights-availability}/search.service:${TAG:-latest}
    build:
      context: .
      dockerfile: FlightsAvailability.Search.Service/Dockerfile
    depends_on:      
      - rabbitmq

  search-service-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:search-service"
    depends_on:
      - search-service

  search-agent-skyscanner:
    image: ${REGISTRY:-flights-availability}/search.agent.skyscanner:${TAG:-latest}
    build:
      context: .
      dockerfile: FlightsAvailability.Search.Agent.Skyscanner/Dockerfile
    depends_on:      
      - rabbitmq

  search-agent-skyscanner-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:search-agent-skyscanner"
    depends_on:
      - search-agent-skyscanner

  search-results-processor-skyscanner:
    image: ${REGISTRY:-flights-availability}/search.results.processor.skyscanner:${TAG:-latest}
    build:
      context: .
      dockerfile: FlightsAvailability.Search.ResultsProcessor.Skyscanner/Dockerfile
    depends_on:      
      - rabbitmq

  search-results-processor-skyscanner-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:search-results-processor-skyscanner"
    depends_on:
      - search-results-processor-skyscanner

  search-agent-amadeus:
    image: ${REGISTRY:-flights-availability}/search.agent.amadeus:${TAG:-latest}
    build:
      context: .
      dockerfile: FlightsAvailability.Search.Agent.Amadeus/Dockerfile
    depends_on:      
      - rabbitmq

  search-agent-amadeus-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:search-agent-amadeus"
    depends_on:
      - search-agent-amadeus

  search-results-processor-amadeus:
    image: ${REGISTRY:-flights-availability}/search.results.processor.amadeus:${TAG:-latest}
    build:
      context: .
      dockerfile: FlightsAvailability.Search.ResultsProcessor.Amadeus/Dockerfile
    depends_on:      
      - rabbitmq

  search-results-processor-amadeus-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:search-results-processor-amadeus"
    depends_on:
      - search-results-processor-amadeus