version: '3.4'

services:

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    ports:
      - "9411:9411"

  search-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5110:80"
      - "50001:50001"

  search-service-dapr:
    command: ["./daprd",
      "-app-id", "search-service",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/flights-availability-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  search-agent-skyscanner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5120:80"
      - "50002:50002"

  search-agent-skyscanner-dapr:
    command: ["./daprd",
      "-app-id", "search-agent-skyscanner",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/flights-availability-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  search-results-processor-skyscanner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5150:80"
      - "50005:50005"

  search-results-processor-skyscanner-dapr:
    command: ["./daprd",
      "-app-id", "search-results-processor-skyscanner",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/flights-availability-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  search-agent-amadeus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5160:80"
      - "50006:50006"

  search-agent-amadeus-dapr:
    command: ["./daprd",
      "-app-id", "search-agent-amadeus",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/flights-availability-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  search-results-processor-amadeus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5140:80"
      - "50004:50004"

  search-results-processor-amadeus-dapr:
    command: ["./daprd",
      "-app-id", "search-results-processor-amadeus",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/flights-availability-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  search-personalization-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5170:80"
      - "50007:50007"

  search-personalization-service-dapr:
    command: ["./daprd",
      "-app-id", "search-personalization-service",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/flights-availability-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
