apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: skyscanner-search-poll
  namespace: flights-availability
spec:
  type: bindings.http
  version: v1
  metadata:
  - name: url
    value: "https://partners.api.skyscanner.net/apiservices/v3/flights/live/search/poll/"